### PR TITLE
Add ability to pass options directly to XO

### PR DESCRIPTION
**Pull request by dflupu**
This lets you run xo with whatever options you like.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I intentionally didn't do this as it's better to put the config in package.json so other things can read it too, like editor plugins.

**Comment by dflupu** [comment]
@sindresorhus There are some cases in which you'd like to use settings different from those in package.json. For example I'm using this with {fix: true} as part of a yeoman generator (it supports gulp plugins) and I want to let the user pass in xo options for the generated files/project.

**Comment by sindresorhus** [comment]
Alright. I'm willing to add it if you can document when to use it and not to use it.

**Comment by dflupu** [comment]
Gave it a shot. Let me know if the description isn't clear enough.

**Pull request merged**
